language: node_js
node_js:
  - "node"

services:
  - mysql

cache:
  directories:
    - "node_modules"

env:
  - DATABASE_URL=mysql://localhost/test

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

script:
  - "npm test"
